# Build settings

markdown: kramdown
permalink: pretty

url: "http://focusaway.com"
#url: "http://127.0.0.1:8000"
baseurl: "/"

port: 8000

#include: ['_includes/work']

sass:
  sass_dir: assets/css
  style: :nested

plugins:
  - jekyll-sitemap
