#-------------------------------
# General Site Settings


title: making videos people want to watch
description: Helping you to get your message across
email: fabrizio.tappero@gmail.com
tel: +34 633 04 8181

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Blog, url: 'blog'}
- {name: Work, url: '#work'}
- {name: About Me, url: '#about-me'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the Internet.
metadata-title: focusaway.com - making viral videos, sports, commercials, ads, advertisement in Barcelona Spain

seo:
  share-title: Focus Away - making advertising videos people want to watch
  description: 'We are a creative business located in Barcelona and dedicated to the creation of on-line videos. From the story crafting all the way to the production of the video. Our work ranges from sports documentaries with Red Bull riders to technical videos on how to build drones.'
  rel-author: 'https://plus.google.com/u/0/107967937093458188059/'
  rel-publisher: 'https://plus.google.com/u/0/107967937093458188059/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I am a videographer based in **Barcelona, Spain** and I
  enjoy the art of telling a good story using videos.
  I specialise in event & advertising videos and sports videos
  but I enjoy short-movie making and peculiar story telling just as much.\\

  If you are interested in knowing more about me, have a look at my works.
  If you are interested in contacting with
  me for a video work, do not hesitate to shoot me an e-mail or call me.
  I don't bite.

skills:
- {name: Good Communication skills. I speak 4 languages, value: '9'}
- {name: Organized and reliable. Very solution-oriented person, value: '7'}
- {name: Resourceful and very hands-on person, value: '8'}
- {name: Video post production knowledge, value: '6'}
- {name: Well connected with other professionals, value: '9'}
- {name: Technically knowledgeable and artistically quite creative, value: '9'}

#-------------------------------
# Work Section

projects: 
- {name: Motorbike World Champion - Adam Raga, folder: 'proj-0', file: 'work/proj-0.html'}
- {name: The Origin of TRS Motorcycles, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: One day With Fox-Head Rider, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Weddings, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Film Festival - ORIANA, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Music Video - Disco Fries, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Restaurant Opening, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Short Film Narrative Analysis, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Actor Reel, folder: 'proj-8', file: 'work/proj-8.html'}
- {name: Theatre Show - The Puppeteer, folder: 'proj-9', file: 'work/proj-9.html'}
- {name: Luxury Homes, folder: 'proj-10', file: 'work/proj-10.html'}
- {name: Wedding Video, folder: 'proj-11', file: 'work/proj-11.html'}
- {name: Behind the Soundtrack, folder: 'proj-12', file: 'work/proj-12.html'}
- {name: C for Cake - Short Film, folder: 'proj-13', file: 'work/proj-13.html'}

#-------------------------------
# Clients Section
clients:

- {avatar: 'face-adam_raga.jpg',
  name: 'Adam Raga',
  title: 'RedBull Rider',
  quote: '<p><strong>Always positive and professional attitude.</strong> Fabrizio was the guy behind my short documentary <i>Equilibrium by Adam Raga</i>. He worked in a very professional manner, he was reliable and always prepared. I am very pleased by the final result of the video and I certainly had a great time during the shooting.</p>',
  logo: 'logo_adamraga.png'}

- {avatar: 'face-moreno_nicoletta.jpg',
  name: 'Moreno Nicoletta',
  title: 'Owner of B&B LOspitalita del Castello',
  quote: '<p><strong>They made for us a great promotional video</strong> of our business activity. They took care of every aspect: locations, shooting, video editing and publishing. We were very pleased by their professionalism, personal touch and of course by the final work.</p>',
  logo: 'logo_lospitalitadelcastello.png'}

- {avatar: 'face-jordi_tarres.jpg',
  name: 'Jordi Tarres',
  title: 'Trial Legend & TRS Technical Manager',
  quote: '<p><strong>A very capable guy.</strong> We met during the shooting of the trial documentary <i>Equilibrium by Adam Raga</i>. Fabrizio created a video advertisement for TRS Motorcycles where he took care of absolutely everything. I am totally pleased by the final result and we are currently working on a second corporate video. I totally recommend him.</p>',
  logo: 'logo_trs.png'}

- {avatar: 'face-bruno_schiavi.jpg',
  name: 'Bruno Schiavi',
  title: 'Manager of onlocations.com',
  quote: '<p><strong>They produced for us excellent video shots.</strong> We manage a large number of properties dealing with lots of customers and we need independent professionals like them. Each single work they did for us was impeccable both from the technical point of view as well as the artistic one. All our customers were very satisfied.</p>',
  logo: 'logo_onlocations.png'}

- {avatar: 'face-nuria_casas.jpg',
  name: 'Nuria Casas',
  title: 'Actress and producer',
  quote: '<p><strong>A very technical person with an artistic side.</strong> He worked for us on the video production of a theatre play in Barcelona. I was certainly impressed by how well he got along with all crew members, to a point in which he cooked a meal for the whole crew of a one-day shooting. He is very creative and reliable at work and a good friend outside work.</p>',
  logo: 'logo_tzsproduccions.png'}

#-------------------------------
# Contact Section

social:
- {icon: 'vimeo', link: 'https://vimeo.com/fabriziotappero'}
- {icon: 'mail2', link: 'mailto:fabrizio.tappero@gmail.com'}
- {icon: 'instagram', link: 'http://www.instagram.com/focusaway/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/fabriziotappero/'}

# these icons are located in /assets/css/fonts/ and have been generated
# using the webpage app https://icomoon.io/
