#-------------------------------
# General Site Settings


title: making videos people want to watch
description: Helping you to get your message across
email: fabrizio.tappero@gmail.com
tel: +34 633 04 8181

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Work, url: '#work'}
- {name: About Me, url: '#about-me'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the Internet.
metadata-title: focusaway.com - making viral videos, sports, commercials, ads, advertisement in Barcelona Spain

seo:
  share-title: Focus Away - making advertisement videos people want to watch
  description: 'We are a creative business located in Barcelona and dedicated to the creation of on-line videos. From the story crafting all the way to the production of the video. Our work ranges from sports documentaries with Red Bull riders to technical videos on how to build drones.'
  rel-author: 'https://plus.google.com/u/0/107967937093458188059/'
  rel-publisher: 'https://plus.google.com/u/0/107967937093458188059/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I am a videographer based in **Barcelona, Spain** and I
  enjoy the art of telling a good story using videos.
  I specialise in event & advertising videos and sports videos
  but I enjoy short-movie making and peculiar story telling just as much.\\

  If you are interested in knowing more about me, have a look at my works.
  If you are interested in contacting with
  me for a video work, do not hesitate to shoot me an e-mail or call me.
  I don't bite.

skills:
- {name: Good Communication skills. I speak 4 languages, value: '9'}
- {name: Organized and reliable. Very solution-oriented person, value: '7'}
- {name: Resourceful and very hands-on person, value: '8'}
- {name: Video post production knowledge, value: '6'}
- {name: Well connected with other professionals, value: '9'}
- {name: Technically knowledgeable and artistically quite creative, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Motorbike World Champion - Adam Raga, folder: 'proj-0', file: 'work/proj-0.html'}
- {name: Trial Documentary - Teaser, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: One day With Fox-Head Rider, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Luxury Homes, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Bed & Breakfast, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Music Video - Disco Fries, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Restaurant Opening, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Short Film Narrative Analysis, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Focus Away Show Reel, folder: 'proj-8', file: 'work/proj-8.html'}
- {name: Theatre Show - The Puppeteer, folder: 'proj-9', file: 'work/proj-9.html'}
#- {name: Wedding Video, folder: 'proj-10', file: 'work/proj-10.html'}


#-------------------------------
# Clients Section

clients:


- {avatar: 'face-adam_raga.jpg',
  name: 'Adam Raga',
  title: 'RedBull Rider',
  quote: '<p><strong>Always positive and professional attitude.</strong> Fabrizio was the guy behind my short documentary <i>Equilibrium by Adam Raga</i>. He worked in a very professional manner, he was reliable and always prepared. I am very pleased by the final result of the video and I certainly had a great time during the shooting.</p>',
  logo: 'logo_adamraga.png'}

- {avatar: 'face-moreno_nicoletta.jpg',
  name: 'Moreno Nicoletta',
  title: 'Owner of B&B LOspitalita del Castello',
  quote: '<p><strong>They made for us a great promotional video</strong> of our business activity. They took care of every aspect: locations, shooting, video editing and publishing. We were very pleased by their professionalism, personal touch and of course by the final work.</p>',
  logo: 'logo_lospitalitadelcastello.png'}

  # - {avatar: 'face-jordi_tarres.jpg',
  #   name: 'Jordi Tarres',
  #   title: 'TRS Motorchicles Tehcnical Manager',
  #   quote: '<p><strong>An interesting guy.</strong> I had the pleasure of meeting .</p>',
  #   logo: 'logo_trs.png'}

- {avatar: 'face-vincent_bardolino.jpg',
  name: 'Vincent Bardolino',
  title: 'Video Editor and Colorist',
  quote: '<p><strong>A cool dude.</strong> I had the chance to work with Fabrizio in the shooting and editing of a few short movies done in Australia and in Barcelona. I can certainly say that I was not disapponted.</p>',
  logo: 'logo_fastbanana.png'}

- {avatar: 'face-bruno_schiavi.jpg',
  name: 'Bruno Schiavi',
  title: 'Manager of onlocations.com',
  quote: '<p><strong>They produced for us excellent video shots.</strong> We manage a large number of properties dealing with lots of customers and we need independent professionals like them. Each single work they did for us was impeccable both from the technical point of view as well as the artistic one. All our customers were very satisfied.</p>',
  logo: 'logo_onlocations.png'}

- {avatar: 'face-nuria_casas.jpg',
  name: 'Nuria Casas',
  title: 'Actress and producer',
  quote: '<p><strong>A very technical person with an artistic side.</strong> He worked for us on the video production of a theatre play in Barcelona. I was certainly impressed by how well he got along with all crew members, to a point in which he cooked a meal for the whole crew of a one-day shooting. He is very creative and reliable at work and a good friend outside work.</p>',
  logo: 'logo_tzsproduccions.png'}

#-------------------------------
# Contact Section

social:
- {icon: 'film', link: 'https://vimeo.com/fabriziotappero'}
- {icon: 'googleplus', link: 'https://plus.google.com/u/0/b/111282084281637799021/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCd0h5xM0vD9JTq61oG-Ep0g/featured'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/fabriziotappero/'}
- {icon: 'github', link: 'https://github.com/fabriziotappero'}

# social network icons available are "home,camera,film,envelope,googleplus,facebook,twitter,youtube,vimeo,github,linkedin"
